# Generated by Django 3.2.6 on 2021-08-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
