# Generated by Django 3.2.6 on 2021-08-29 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_rename_photo_foods_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foods',
            name='rate',
        ),
    ]
