# Generated by Django 3.2.6 on 2021-08-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_foods_type_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foods',
            name='type_food',
            field=models.CharField(choices=[('*', 'All'), ('drinks', 'Drinks'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], default='*', max_length=50),
        ),
    ]
