# Generated by Django 3.2.7 on 2021-09-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0002_sliders_iamges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliders',
            name='descriptions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sliders',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
