# Generated by Django 3.2.6 on 2021-09-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuffs',
            name='image',
            field=models.ImageField(blank=True, upload_to='stuff/'),
        ),
    ]
