# Generated by Django 3.2.6 on 2021-09-05 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_stuffs_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stuffs',
            old_name='insta',
            new_name='instagram',
        ),
    ]
